### ISSUE TITLE
BasePath

### ISSUE THREAD

**Issue by oelegeirnaert** [keijack/python-simple-http-server#1]
Hello, 

Thanks for creating this project!
I need to serve a file which is located two levels higher than the file the server is being started.
Is there any way to provide the basepath when starting the simple-http-server?

Thanks in advance!
Oele

**Comment by oelegeirnaert** [comment]
Sorry, I solved the problem by using the "return StaticFile(my_picture, "image/jpg")"

**Comment by keijack** [comment]
Thanks for choosing, this requirement is reasonable. In fact I am considering to add a `public` path to hold all the static files.

**Comment by keijack** [comment]
try to startup server use:

    server.start(resources={"/path_prefix/*", "/absolute/dir/root/path",
                            "/path_prefix/*", "/absolute/dir/root/path"})
