### ISSUE TITLE
Bypassing routing for certain directories

### ISSUE THREAD

**Issue by jasonmhead** [keijack/python-simple-http-server#10]
Is there a way to bypass the routing for certain directories other than creating a route that returns a static file?

**Comment by keijack** [comment]
If you want to specify the resources path:

    server.start(resources={"/path_prefix/*", "/absolute/dir/root/path", # Match the files in the given folder with a special path prefix.
                            "/path_prefix/**", "/absolute/dir/root/path", # Match all the files in the given folder and its sub-folders with a special path prefix.
                            "*.suffix", "/absolute/dir/root/path", # Match the specific files in the given folder.
                            "**.suffix", "/absolute/dir/root/path", # Match the specific files in the given folder and its sub-folders.
                            })

**Comment by jasonmhead** [comment]
thank you
