### ISSUE TITLE
GET 请求时 URL 长度限制是多少

### ISSUE THREAD

**Issue by StupidQu** [keijack/python-simple-http-server#12]
我在试用 superagent 请求用这个模块搭建的服务器时，发现 POST 请求会返回 400，大概是因为 POST 请求没有一次把数据发送到服务器端。当我尝试换用 GET 时发现 GET 有 URL 长度限制，请问这个长度限制是多少

**Comment by keijack** [comment]
The max bytes in a line is set to 65536 which includes the the command(method) like GET/POST, and version like (HTTP/1.1). And you should be aware that if a character is encoded, like most of the Chinese characters and the reserved HTTP characters like %, it should be considered as 3 bytes to transfer.

**Comment by keijack** [comment]
Close for no response for a long time, if you have any other problem, please re-open this issue.
