### ISSUE TITLE
Not having to stop and restart the server every time I make changes

### ISSUE THREAD

**Issue by jose-sampedro** [keijack/python-simple-http-server#15]
Hi,

Every time I modify a controller I have to close the script and run it again for the changes to take effect.

To develop it becomes very tedious.

How do you do it? Any suggestions?

THX!

**Comment by keijack** [comment]
Yes，I will restart the server every time I make some changes. But let me think it out whether the server can restart when some controller is changed.

**Comment by keijack** [comment]
https://gitee.com/keijack/python-simple-http-server-demo
Please check the demo above, there is a `dev.py` in the folder, which using `watchdog` to watch file changes and do a server restart when modify events received.

**Comment by keijack** [comment]
Close for long time silence, if you have any problem, please re-open this issue or submit a new one.
