### ISSUE TITLE
Issue with rename project

### ISSUE THREAD

**Issue by kloczek** [keijack/python-simple-http-server#16]
Looks like https://github.com/keijack/python-simple-http-server/ project has been rename first by rename git repo (so original repo URL gone) and mow by forking https://github.com/naja-atra/naja-atra/.
Result of that fork is that in https://github.com/keijack/python-simple-http-server/ all version tags has been removed.
Second thing is that on pypi `naja-atra` still is not registered.

If this project really no longer will be maintained under `python-simple-http-server` name IMO whole rename should be done a bit different:
- https://github.com/keijack/python-simple-http-server/ should be left as it was
- https://github.com/keijack/python-simple-http-server/ repo should be forked to here
- https://github.com/keijack/python-simple-http-server/ should receive last commit in README.md about project rename
- https://github.com/keijack/python-simple-http-server/ status sholuld be changed to read-only.

With above still will be possible to have access to git tags in old repo.

**Comment by keijack** [comment]
Thanks for suggesting.
