### ISSUE TITLE
Why this project and not flask?

### ISSUE THREAD

**Issue by dinuta** [keijack/python-simple-http-server#2]
HI @keijack,

Why this webserver and not Flask. What features do you have, or usability that Flask doesn't have?

Catalin

**Comment by dinuta** [comment]
I see 2 points here:
- you wanna bring spring flavor here by scanning controllers from packages and filter chain

Will you work on thread safety?

Does this server can be used with uwsgi?

**Comment by keijack** [comment]
This is a very simple project, event not supporting SSL, it's only use for some inner API gateway in a very light way mode. It's safe where every request works in its own thread, but If you start multiple threads to proceed ONE request, and try to set header to the Request object in different threads, it's not safe to do that.
