### ISSUE TITLE
Missing version tag(s)

### ISSUE THREAD

**Issue by kloczek** [keijack/python-simple-http-server#5]
According to https://pypi.org/project/simple-http-server/ latest version of the 
python-simple-http-server is 0.11.4 but there is no any version git tags in this repo.
Is it possible to add at least last version tag?

**Comment by keijack** [comment]
Of course，I'll add new tags when a new version is being released afterward.

**Comment by keijack** [comment]
I close this, if you have any problem, please reopen it again or submit another issue.

**Comment by kloczek** [comment]
Thamk you.
