### ISSUE TITLE
after a period of time, the service will shut down automatically

### ISSUE THREAD

**Issue by kxg3030** [keijack/python-simple-http-server#6]

**Comment by keijack** [comment]
Could you please give me some logs before the server shut down?

**Comment by kxg3030** [comment]
I use supervisor to manage my Python application. It will restart automatically after a period of time without any error log. Maybe it's not the problem of this package. Thank you

**Comment by keijack** [comment]
OK. I close this then, if you have any other problem, please reopen it or submit another issue.
