### ISSUE TITLE
Minimum required components to get running?

### ISSUE THREAD

**Issue by jasonmhead** [keijack/python-simple-http-server#8]
Hello, it seems I wasn't able to access the server via localhost and set port.
What is the minimum code / component requirement setup to serve a route?

**Comment by keijack** [comment]
You should at least define a controller function:

    from simple_http_server import route, server
        
    @route("/")
    def index():
        return {"hello": "world"}   
    
    server.start(port=9090)

**Comment by jasonmhead** [comment]
Thanks! 
Got it working.
